# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a935b99b80ddf04b05d1c54ca919576c04b7be6e4816c603a37b9f7d05886262915538a8f6732f1ad326a705e6c1e4bc5a9c6a9ca94af9e133a728438ca214ef

test:
  secret_key_base: 548962924a70e4a648dfd3f9fd95af818792ee6909a678e87176ae6434985f5dba08631c76959ccbad660c9af582133ee0ddd5ef1919bed7e4b186eadfdc8df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
